[package]
name = "sqlite2json"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
serde_json = "1.0"

[profile.release]
strip = true
lto = true
